import type { Metadata } from 'next';

import '@/app/_lib/components/globals.css';
import { Noto_Sans_JP } from 'next/font/google';
import { ApiStoreProvider } from './_lib/store/client/api';

/**
 * `fetch` の `cache` option が見指定のときに `no-store` を設定
 * 基本的に、fetch の結果を static file に cache しない
 */
export const fetchCache = 'default-no-store';

/**
 * SSR を矯正 (SSG が必要な場合は個別に `export const dynamic = 'auto' or 'force-static'` を指定する)
 */
export const dynamic = 'force-dynamic';

const noto = Noto_Sans_JP({
  subsets: ['cyrillic', 'latin', 'latin-ext', 'vietnamese'],
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto.className}>
        <ApiStoreProvider>{children}</ApiStoreProvider>
      </body>
    </html>
  );
}
